import { access, writeFile } from "node:fs/promises";
import path from "node:path";
import { diagnoseRepository, type RepositoryInitDiagnosticsOptions } from "@meguribi/adapters";
import type { AgentDiagnosis, RepositoryInitDiagnostics } from "@meguribi/core";
import type { DoctorCommandOptions, DoctorDependencies } from "../program.js";

export interface InitCommandOptions {
  json?: boolean;
  nonInteractive?: boolean;
  implementer?: string;
}

export interface InitResult {
  repository: RepositoryInitDiagnostics;
  agent: AgentDiagnosis;
  configPath: string;
  configAction: "created" | "existing";
  runnable: boolean;
}

export interface InitCommandDependencies extends DoctorDependencies {
  diagnoseRepository?: typeof diagnoseRepository;
  runDoctor?: (
    options: DoctorCommandOptions,
    deps: DoctorDependencies,
  ) => Promise<{ exitCode: number; diagnosis: AgentDiagnosis }>;
  cwd?: string;
  stdout?: (text: string) => void;
  stderr?: (text: string) => void;
}

function configTemplate(implementer: string): string {
  return [
    "# Generated by meguribi init. Review this file before delivery runs.",
    `implementer: ${implementer}`,
    `${implementer}:`,
    "  transport: acp",
    "  inheritedMcpPolicy: warn",
    "",
  ].join("\n");
}

async function createConfigIfMissing(
  repositoryPath: string,
  implementer: string,
): Promise<{ configPath: string; configAction: "created" | "existing" }> {
  const configPath = path.join(repositoryPath, ".meguribi.yml");
  try {
    await access(configPath);
    return { configPath, configAction: "existing" };
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  try {
    await writeFile(configPath, configTemplate(implementer), { encoding: "utf8", flag: "wx" });
    return { configPath, configAction: "created" };
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "EEXIST") {
      return { configPath, configAction: "existing" };
    }
    throw new Error(`Unable to create ${configPath}; check directory permissions and retry`);
  }
}

function formatDependency(dependency: InitResult["repository"]["dependencies"][number]): string {
  const status = dependency.status === "available" ? "available" : dependency.status;
  return dependency.nextAction ? `${status} — ${dependency.nextAction}` : status;
}

function formatHuman(result: InitResult): string {
  const lines = [
    `Repository: ${result.repository.repository ?? "unknown"}`,
    `Path: ${result.repository.repositoryPath}`,
    `Default branch: ${result.repository.defaultBranch ?? "unknown"}`,
    "Dependencies:",
    ...result.repository.dependencies.map(
      (dependency) =>
        `- ${dependency.name}: ${formatDependency(dependency)}${dependency.version ? ` (${dependency.version})` : ""}`,
    ),
    `Agent runnable: ${result.agent.runnable ? "yes" : "no"}`,
    `Config: ${result.configAction} (${result.configPath})`,
  ];
  if (result.repository.warnings.length > 0) {
    lines.push("Warnings:", ...result.repository.warnings.map((warning) => `- ${warning}`));
  }
  if (result.repository.errors.length > 0) {
    lines.push("Errors:", ...result.repository.errors.map((error) => `- ${error}`));
  }
  return `${lines.join("\n")}\n`;
}

export async function runInit(
  targetPath: string | undefined,
  options: InitCommandOptions = {},
  deps: InitCommandDependencies = {},
): Promise<{ exitCode: number; result: InitResult }> {
  const requestedPath = targetPath ?? deps.cwd ?? process.cwd();
  if (options.implementer !== "devin" && options.implementer !== "cursor") {
    throw new Error(
      "init requires --implementer devin|cursor so the selected agent can be diagnosed",
    );
  }
  const inspect = deps.diagnoseRepository ?? diagnoseRepository;
  const repository = await inspect({
    repositoryPath: requestedPath,
    runner: undefined,
  } satisfies RepositoryInitDiagnosticsOptions);
  const config = await createConfigIfMissing(repository.repositoryPath, options.implementer);
  const doctor = deps.runDoctor ?? (await import("../program.js")).runDoctor;
  const agentResult = await doctor(
    {
      json: true,
      nonInteractive: options.nonInteractive,
      implementer: options.implementer,
    },
    { ...deps, cwd: repository.repositoryPath, stdout: () => undefined },
  );
  const result: InitResult = {
    repository,
    agent: agentResult.diagnosis,
    configPath: config.configPath,
    configAction: config.configAction,
    runnable: repository.runnable && agentResult.diagnosis.runnable,
  };
  const writeOut = deps.stdout ?? ((text: string) => process.stdout.write(text));
  if (options.json) {
    writeOut(`${JSON.stringify(result, null, 2)}\n`);
  } else {
    writeOut(formatHuman(result));
  }
  return { exitCode: result.runnable ? 0 : 1, result };
}
