import { measureRelease, type MeasurementArtifact, type MeasureDependencies } from "@meguribi/core";
import { parseIssueTarget } from "../target.js";
export interface MeasureCommandOptions { json?: boolean; local?: boolean; repoPath?: string; period?: string }
export interface MeasureCommandDependencies { measure?: MeasureDependencies; measureRelease?: typeof measureRelease; createMeasureDependencies?: (options: { cwd: string; repositoryPath: string; repository: string; localOnly: boolean }) => Promise<MeasureDependencies>; cwd?: string; stdout?: (text: string) => void }
export async function runMeasureCommand(target: string, options: MeasureCommandOptions = {}, deps: MeasureCommandDependencies = {}): Promise<{ exitCode: number; result?: Awaited<ReturnType<typeof measureRelease>> }> {
  const parsed = parseIssueTarget(target); const cwd = deps.cwd ?? process.cwd(); const repositoryPath = options.repoPath ?? cwd; if (!options.period) throw new Error("--period is required");
  const dependencies = deps.measure ?? await (deps.createMeasureDependencies ?? (async (wiringOptions) => { const wiring = await import("../wiring/create-delivery-deps.js"); return wiring.createMeasureDependencies(wiringOptions); }))({ cwd, repositoryPath, repository: parsed.repository, localOnly: options.local === true });
  const result = await (deps.measureRelease ?? measureRelease)({ repository: parsed.repository, issueNumber: parsed.issueNumber, period: options.period }, dependencies); const writeOut = deps.stdout ?? ((text: string) => process.stdout.write(text)); writeOut(options.json ? `${JSON.stringify(result, null, 2)}\n` : formatHuman(result)); return { exitCode: 0, result };
}
function formatHuman(result: { artifact: MeasurementArtifact; artifactPath: string; commentId: number }): string { return [`Measurement draft: PR #${String(result.artifact.pullRequestNumber)}`, `Period: ${result.artifact.period.from} to ${result.artifact.period.to}`, `Result: ${result.artifact.result}`, `Open questions: ${result.artifact.openQuestions.join(", ")}`, `Artifact: ${result.artifactPath}`, `Issue comment: #${String(result.commentId)}`, "Human evaluation required: yes", ""].join("\n"); }
