import { requireSolution, type RequirementArtifact, type RequireDependencies } from "@meguribi/core";
import { parseIssueTarget } from "../target.js";
export interface RequireCommandOptions { json?: boolean; local?: boolean; repoPath?: string; solution?: number }
export interface RequireCommandDependencies { require?: RequireDependencies; requireSolution?: typeof requireSolution; createRequireDependencies?: (options: { cwd: string; repositoryPath: string; repository: string; localOnly: boolean }) => Promise<RequireDependencies>; cwd?: string; stdout?: (text: string) => void }
export async function runRequireCommand(target: string, options: RequireCommandOptions = {}, deps: RequireCommandDependencies = {}): Promise<{ exitCode: number; result?: Awaited<ReturnType<typeof requireSolution>> }> {
  const parsed = parseIssueTarget(target); const cwd = deps.cwd ?? process.cwd(); const repositoryPath = options.repoPath ?? cwd; if (options.solution === undefined) throw new Error("--solution is required");
  const dependencies = deps.require ?? await (deps.createRequireDependencies ?? (async (wiringOptions) => { const wiring = await import("../wiring/create-delivery-deps.js"); return wiring.createRequireDependencies(wiringOptions); }))({ cwd, repositoryPath, repository: parsed.repository, localOnly: options.local === true });
  const result = await (deps.requireSolution ?? requireSolution)({ repository: parsed.repository, issueNumber: parsed.issueNumber, solutionNumber: options.solution }, dependencies); const writeOut = deps.stdout ?? ((text: string) => process.stdout.write(text)); writeOut(options.json ? `${JSON.stringify(result, null, 2)}\n` : formatHuman(result)); return { exitCode: 0, result };
}
function formatHuman(result: { artifact: RequirementArtifact; artifactPath: string; commentId: number }): string { return [`Requirement draft: solution ${String(result.artifact.selectedSolution.number)}`, `Requirements: ${String(result.artifact.requirements.length)}`, `Open questions: ${result.artifact.openQuestions.join(", ")}`, `Artifact: ${result.artifactPath}`, `Issue comment: #${String(result.commentId)}`, "Human approval required: yes", ""].join("\n"); }
